class TestBasicModelViewModel extends Backbone.Model
class TestCompositeModelViewModel extends Backbone.Model

@TestBasicModelViewModel = TestBasicModelViewModel
@TestCompositeModelViewModel = TestCompositeModelViewModel