// Generated by CoffeeScript 1.6.3
(function() {
  var TestBasicModelViewModel, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TestBasicModelViewModel = (function(_super) {
    __extends(TestBasicModelViewModel, _super);

    function TestBasicModelViewModel() {
      _ref = TestBasicModelViewModel.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return TestBasicModelViewModel;

  })(Backbone.Model);

  this.TestBasicModelViewModel = TestBasicModelViewModel;

}).call(this);
