// Generated by CoffeeScript 1.6.3
(function() {
  var loadTemplates, templates;

  templates = ['guts-basicmodelview-test'];

  loadTemplates = function() {
    var getTemplate, template_name, templates_loaded, _i, _len, _results;
    templates_loaded = 0;
    getTemplate = function(template_name) {
      return $.get("templates/" + template_name + ".hbs", function(template) {
        var $template_script, htmlReporter, jasmineEnv;
        $template_script = $("<script type='text/x-handlebars-template' id='" + template_name + "'></script>");
        $template_script.text(template);
        $('head').append($template_script);
        templates_loaded += 1;
        if (templates_loaded === templates.length) {
          window.runTests();
          jasmineEnv = jasmine.getEnv();
          htmlReporter = new jasmine.HtmlReporter();
          jasmineEnv.addReporter(htmlReporter);
          return jasmineEnv.execute();
        }
      });
    };
    _results = [];
    for (_i = 0, _len = templates.length; _i < _len; _i++) {
      template_name = templates[_i];
      _results.push(getTemplate(template_name));
    }
    return _results;
  };

  $(function() {
    return loadTemplates();
  });

}).call(this);
