// Generated by CoffeeScript 1.6.3
(function() {
  Guts.render = function(template_name, context) {
    var source, template;
    source = $("#" + template_name).html();
    template = Handlebars.compile(source);
    if (template) {
      return template(context);
    } else {
      throw "handlebars_render : error : couldn't find template '" + template_name + "'";
    }
  };

  window.runTests = function() {
    return describe("BasicModelView", function() {
      var $element, model, view;
      $element = $("<div class='guts-basicmodelview-test'></div>");
      $('body').append($element);
      model = new TestBasicModelViewModel({
        title: 'Test Model',
        description: 'I am for testing!'
      });
      view = new TestBasicModelView({
        model: model,
        el: $('.guts-basicmodelview-test')
      });
      return it("Renders to the page", function() {
        var description, title;
        title = $element.children('#bmv-title').text();
        description = $element.children('#bmv-description').text();
        expect(title).toEqual(model.get('title'));
        return expect(description).toEqual(model.get('description'));
      });
    });
  };

}).call(this);
