// Generated by CoffeeScript 1.6.3
(function() {
  var TestBasicModelView, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TestBasicModelView = (function(_super) {
    __extends(TestBasicModelView, _super);

    function TestBasicModelView() {
      _ref = TestBasicModelView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    TestBasicModelView.prototype.className = 'guts-basicmodelview-test';

    TestBasicModelView.prototype.change = true;

    return TestBasicModelView;

  })(Guts.BasicModelView);

  this.TestBasicModelView = TestBasicModelView;

}).call(this);
